"""
export.py — read SQLite + config.json and write data.js next to dashboard.html.

The dashboard loads data via  <script src="data.js">  (NOT fetch), so it works
straight from file:// with zero server. The bot token is deliberately never
written into data.js.
"""

import json
import os

import db

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(BASE_DIR, "config.json")
DATA_JS_PATH = os.path.join(BASE_DIR, "data.js")


def load_config():
    with open(CONFIG_PATH, encoding="utf-8") as f:
        return json.load(f)


def export():
    """Regenerate data.js from the database. Called after every bot message."""
    config = load_config()

    rows = [
        {
            "id": r["id"],
            "date": r["date"],
            "category": r["category"],
            "amount": r["amount"],
            "note": r["note"] or "",
            "type": r["type"],
        }
        for r in db.all_rows()
    ]

    # Everything the dashboard needs — and never the bot token.
    public_config = {
        "currency": config.get("currency", "₹"),
        "monthlyBudget": config.get("monthlyBudget", 0),
        "budgets": config.get("budgets", {}),
    }

    content = (
        "// Auto-generated by export.py — do not edit by hand.\n"
        f"window.EXPENSE_DATA = {json.dumps(rows, ensure_ascii=False, indent=1)};\n"
        f"window.EXPENSE_CONFIG = {json.dumps(public_config, ensure_ascii=False, indent=1)};\n"
    )
    with open(DATA_JS_PATH, "w", encoding="utf-8") as f:
        f.write(content)
    return len(rows)


if __name__ == "__main__":
    n = export()
    print(f"Wrote {n} transactions to {DATA_JS_PATH}")
